apiVersion: v1
kind: Pod
metadata:
  name: simple-pods
  labels:
    env: demo-pods
spec:
  containers:
  - name: nginx
    image: nginx:1.27
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 80
