apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    name: pod-1-demo
spec:
  containers:
  - name: nginx
    image: nginx:1.27
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 80
# this pod is only fro default namespace 
