apiVersion: v1
kind: Service # service is the resources 
metadata:
  name: service-ip-default
spec:
  type: ClusterIP # even if you didnt enter this it will be default
  ports:
  - port: 80
  selector:
    env: demo # this will match the enviroment vavriable with every other pod in this node 


