apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    name: pod1
spec:
  containers:
  - name: nginx-1
    image: nginx
    ports:
    - containerPort: 80
  nodeSelector:
    gpu: "true"






