apiVersion: v1
kind: Service # service is the resources 
metadata:
  name: service-clusterip
spec:
  type: ClusterIP # even if you didnt enter this it will be default
  ports:
  - port: 80
    targetPort: 80
  selector:
    env: demo # this will match the enviroment variable with every other pod in this node and give the cluster ip if it is matched


