apiVersion: v1
kind: Pod
metadata:
  name: simple-pod
  labels:
    name: simple
spec:
  containers:
  - name: nginx-1
    image: nginx
    resources:
      requests:
        memory: "100Mi"
      limits:
        memory: "200Mi"
        cpu: "500m" # not a good idea to limit the cpu 
    ports:
    - containerPort: 80
