apiVersion: v1
kind: ReplicationController
metadata: # metadata for replica
  name: replica-set
  labels:
    env: demo
spec: # sep for replica
  template:
    metadata:
      name: nginx-pod
      labels:
        env: demo
    spec: # spec for the pods
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 8000
  replicas: 3 # how many repicas do you want 
  selector:
    matchLabels:
      env: demo

