apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
  labels:
    name: demo-pod
spec:
  containers:
  - name: myapp-container
    image: busybox:1.28
    command: ['sh', '-c', 'echo running the app contianers && sleep 3600']
    ports:
    - containerPort: 80
    env:
    - name: FIRSTNAME
      value: "Nischal"
  initContainers:
  - name: init-container
    image: busybox:1.28
    command: ['sh', '-c']
    args: ['until nslookup myservice.default.svc.cluster.local; do echo waiting fro the service to run; sleep 2; done ']






