apiVersion: v1
kind: Pod
metadata:
  name: pds-container
  labels:
    env: pods-env
spec:
  containers:
  - name: nginx-container
    image: nginx:1.27.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 8000
