apiVersion: v1
kind: Pod
metadata:
  name: simple-pod
  labels:
    name: simple
spec:
  containers:
  - name: nginx-1
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 80
