apiVersion: v1
kind: ReplicationController
metadata:
  name: replica-cont
  labels:
    env: demo
spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        env: demo
    spec:
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 8000
  replicas: 3
